## Splunk app configuration file

[install]
is_configured = false
state = enabled
build = 1

[launcher]
author = Paul Metcalf
version = 1.1.0
description = Technology Add-on for pfSense logs, including DNSBL and pfBlockerNG IP.

[ui]
is_visible = false
label = TA-pfsense Plus

[package]
id = ta-pfsense-plus
check_for_updates = true

[id]
name = ta-pfsense-plus
version = 1.1.0

[triggers]
reload.lookup_table_files = simple
reload.lookup-table-files = simple
