[pfsense_filterlog]
search = sourcetype=pfsense:filterlog
[pfsense_openvpn_authentication]
search = sourcetype=pfsense:openvpn user=*
[pfsense_openvpn]
search = sourcetype=pfsense:openvpn
[pfsense_dhcpd]
search = sourcetype=pfsense:dhcpd
[pfsense_keadhcp]
search = sourcetype=pfsense:kea-dhcp4 vendor_action=*
[pfsense_nginx]
search = sourcetype=pfsense:nginx

[pfsense_unbound]
search = sourcetype=pfsense:unbound

[pfsense_suricata]
search = sourcetype=pfsense:suricata action!=Error
