[pfsense_filter_rule_map]
filename = $SPLUNK_HOME/etc/apps/ta-pfsense-plus/lookups/pfsense_filter_rule_map.csv

[pfsense_interface_map]
filename = $SPLUNK_HOME/etc/apps/ta-pfsense-plus/lookups/pfsense_interface_map.csv

[pfsense_dns_hosts]
filename = $SPLUNK_HOME/etc/apps/ta-pfsense-plus/lookups/pfsense_dns_hosts.csv
