[pfsense_application_protocols]
filename = pfsense_application_protocols.csv

[pfsense_filter_action]
filename = pfsense_filter_action.csv

[pfsense_filter_app]
filename = pfsense_filter_app.csv

[pfsense_filter_direction]
filename = pfsense_filter_direction.csv

[pfsense_filter_tcpflags]
filename = pfsense_filter_tcpflags.csv

[pfsense_filter_transport]
filename = pfsense_filter_transport.csv

[pfsense_kea_dhcp_action]
filename = pfsense_kea_dhcp_action.csv

[pfsense_openvpn_action]
filename = pfsense_openvpn_action.csv

[pfsense_snort_action]
filename = pfsense_snort_action.csv

[pfsense_snort_severity]
filename = pfsense_snort_severity.csv

[pfsense_suricata_action]
filename = pfsense_suricata_action.csv

[pfsense_suricata_severity]
filename = pfsense_suricata_severity.csv

[pfsense_filter_rule_map]
filename = pfsense_filter_rule_map.csv

[pfsense_dns_hosts]
filename = pfsense_dns_hosts.csv

[pfsense_interface_map]
filename = pfsense_interface_map.csv
