[pfsense_filter_rule_map]
filename = pfsense_filter_rule_map_enrichment.csv

[pfsense_interface_map]
filename = pfsense_interface_map_enrichment.csv

[pfsense_dns_hosts]
filename = pfsense_dns_hosts_enrichment.csv

[pfsense_zone_subnets]
filename = pfsense_zone_subnets_enrichment.csv

[pfsense_alias_ports]
filename = pfsense_alias_ports_enrichment.csv

[pfsense_interface_ips]
filename = pfsense_interface_ips_enrichment.csv

[pfsense_gateway_ips]
filename = pfsense_gateway_ips_enrichment.csv
