# Macro definitions for pfSense TA

[pfsense_enrich_ip_tags]
definition = lookup pfsense_zone_subnets cidr as src_ip_norm OUTPUT zone as src_zone | lookup pfsense_zone_subnets cidr as dest_ip_norm OUTPUT zone as dest_zone | lookup pfsense_interface_ips ip as src_ip_norm OUTPUT interface as src_interface | lookup pfsense_interface_ips ip as dest_ip_norm OUTPUT interface as dest_interface | lookup pfsense_gateway_ips ip as src_ip_norm OUTPUT name as src_gateway | lookup pfsense_gateway_ips ip as dest_ip_norm OUTPUT name as dest_gateway | eval src_tags=mvappend(src_zone, src_interface, src_gateway), dest_tags=mvappend(dest_zone, dest_interface, dest_gateway)
iseval = 0

[pfsense_enrich_dns]
definition = lookup pfsense_dns_hosts ip as src_ip_norm OUTPUT hostname as src_host_lookup | lookup pfsense_dns_hosts ip as dest_ip_norm OUTPUT hostname as dest_host_lookup
iseval = 0
