# Macro definitions for pfSense TA

[pfsense_enrich_ip_tags]
definition = lookup pfsense_zone_subnets cidr as src_ip_norm OUTPUT zone as src_zone | lookup pfsense_zone_subnets cidr as dest_ip_norm OUTPUT zone as dest_zone | eval src_tags=src_zone, dest_tags=dest_zone
iseval = 0

[pfsense_enrich_dns]
definition = lookup pfsense_dns_hosts ip as src_ip_norm OUTPUT hostname as src_host_lookup | lookup pfsense_dns_hosts ip as dest_ip_norm OUTPUT hostname as dest_host_lookup
iseval = 0
